### ISSUE TITLE
Wrong path in 2.3.0-pl-Package

### ISSUE THREAD

**Issue by frischnetz** [Jako/ImagePlus#1]
manager looks for imageplus components in
/assets/components/delicart/ 
instead of 
/assets/components/imageplus/

(renaming assets/components/imageplus to assets/components/delicart as a test restores function)

**Comment by Jako** [comment]
Fixed asap.

Von meinem iPhone gesendet

**Comment by Jako** [comment]
Fixed. Thanks for reporting the issue.
