### ISSUE TITLE
[Feature request] Force to view crop screen right after image upload

### ISSUE THREAD

**Issue by vierkantemeter** [Jako/ImagePlus#10]
It would be ideal to have an image+ setting which make the crop screen pop-up automatically after the user uploads an image. In my experience, the end-user will forget to crop the image after he uploaded it.

**Comment by Jako** [comment]
Fixed.

**Comment by vierkantemeter** [comment]
Awesome, thanks!

**Comment by vierkantemeter** [comment]
Just donated you a beer :beer:

**Comment by Jako** [comment]
Thanks, Prost :beer:
