### ISSUE TITLE
property "options" of snippet "ImagePlus" doesn't work in version 2.8.6

### ISSUE THREAD

**Issue by halftrainedharry** [Jako/ImagePlus#107]
It seems that in the newest version, the code expects the value of the property "options" to be JSON.

https://github.com/Jako/ImagePlus/blob/fca05c7a807789d76405e83435596c5b8404a160/core/components/imageplus/src/Snippets/ImagePlus.php#L28

If you provide a value like ``&options=`w=100` `` (or ``&options=`&w=100` ``), it gets deleted.

MODX Forum Discussion:
https://community.modx.com/t/image-tv-not-creating-downsized-thumbnail-while-using-migxdb/4947

**Comment by Jako** [comment]
Thanks, thats true:

please change it to ```'options' => '',``` until a fix is released.

**Comment by Jako** [comment]
Fixed with 2.8.7
