### ISSUE TITLE
Error after upgrading to 2.8.8

### ISSUE THREAD

**Issue by SnowCreative** [Jako/ImagePlus#108]
Since upgrading to Image+ 2.8.8, my logs fill up with this error when editing resources in the manager:

[2022-02-16 21:35:43] (ERROR in ImagePlus Plugin @ [PATH TO CORE]/cache/includes/elements/modplugin/18.include.cache.php : 29) TreehillStudio\ImagePlus\Plugins\Events\OnDocFormRender was not found!

**Comment by Jako** [comment]
Sorry, I have tested the cleanup resolver only locally and it worked well. But I forgot to add it to the package. It is fixed with 2.8.8-pl2.

**Comment by SnowCreative** [comment]
OK, found one thing:
The stylesheet "colorpicker.css" is not loading, so it is getting redirected, slowing down the page loading a lot. The HTML call is this (in the TV tab when editing a resource):

<div class="x-form-element modx-tv-form-element">
<input type="hidden" id="tvdef167" value="" />
<link rel="stylesheet" href="/assets//components/colorpicker/css/colorpicker.css" />

There is a double slash after "assets", but even without the double slash this file does not exist. If have have 10 colorpicker TVs linked to a resource, this line to load the CSS appears in all ten of the HTML blocks for the TVs, making the page loading slow to a crawl.

Where is this extra slash getting inserted? There is also this, in the HEAD of the page:

<link href="/assets/components/colorpicker/css/mgr/colorpicker.min.css?v=v2.0.1" rel="stylesheet" type="text/css" />

which loads the correct style sheet.

**Comment by Jako** [comment]
Is it possible, that you have two Colorpicker plugins active for some reason?

**Comment by SnowCreative** [comment]
Whoops, sorry — I've been leaving these comments here instead of in the ColorPicker project! Can you move them??

**Comment by Jako** [comment]
Can you add the first comment to the ColorPicker issue? Then I will answer there and so on. I can't move the comments.

Can you zip those `manager>templates>default>element>tv>` folders  and send them by mail please (contact is in my profile). Then I will try to replicate the issue.

**Comment by Jako** [comment]
The ColorPicker issue is fixed with 2.0.2. Some very old files from before 1.0.3 were never deleted from the core and manager folders.

**Comment by SnowCreative** [comment]
> The ColorPicker issue is fixed with 2.0.2. Some very old files from before 1.0.3 were never deleted from the core and manager folders.

Yay! It's all working now!
