### ISSUE TITLE
Bug: Reset of other TVs resets the Image

### ISSUE THREAD

**Issue by inreti** [Jako/ImagePlus#12]
When you click on the reset icon right before any other TV in a resource, the imageplus image is also reset.

**Comment by Jako** [comment]
If you want to fix that yourself, the code around here: https://github.com/Jako/ImagePlus/blob/master/assets/components/imageplus/mgr/js/imageplus.panel.input.js#L77-L84

Otherwise I'll fix it with 2.4.0.
