### ISSUE TITLE
SVG not supported/No clear way to deny user from uploading an SVG

### ISSUE THREAD

**Issue by rllyPhoenix** [Jako/ImagePlus#120]
Right now when you upload an SVG using Image+ you cannot crop it nor pThumb, which makes sense. Then again there is no clear way to deny the user from uploading an SVG like you can when using a normal Image TV (Before some of you reply why not use a normal Image TV: I need to use image+ for what i am trying to do). 

Any help/update is appreciated!

**Comment by Jako** [comment]
You have to use a media source for the TV that can't list SVG files.
