### ISSUE TITLE
Error "Unable to decode json" when image width exceeds 4921px

### ISSUE THREAD

**Issue by vierkantemeter** [Jako/ImagePlus#14]
Just ran into this bug. After extensive testing I came to following conclusion: When an image with a width of 4921px is uploaded, anything works fine. When an image with a width of 4922px (or more) is uploaded, the front-end renders the white screen of dead with the following error in the errorlog:

```(ERROR @ /index.php) [Image+] Unable to decode json - are you sure this is an Image+ TV?```

This bug is related to Image+, because when I use a regular image TV and output it with a pthumb modifier, everything is working normal, even with the 4922px image.

I know you should actually downscale the images a bit first before uploading, but many of my customers upload images directly from their digital camera... :tired_face:

If you need more info, please let me know.

Environment:
MODX 2.4.0-pl
Image+ 2.3.3
pThumb 2.3.4

**Comment by Jako** [comment]
Could you first try the [2.4.0-b3](http://extras.partout.info/download/imageplus-2.4.0-b3.zip). Maybe the frontend issue is solved there.

If it does not work: Which thumbnail solution is installed? Do you have issues in the backend too?

**Comment by vierkantemeter** [comment]
Thanks for your reply. I'm not able to install the update, because the site where this happens will go live today. I'm a bit afraid I will lose all the image+ TV values and crops when I deinstall 2.3.4 and install 2.4.0. Do you know if I can safely deinstall the old version and install the new one without losing everything? I can't update image+ because 2.4.0 does appear as a new package instead of an update for 2.3.4.

![voila_capture 2015-09-03_10-41-52_am](https://cloud.githubusercontent.com/assets/487567/9654072/6af11c58-5228-11e5-9642-2589d3d1b791.jpg)

**Comment by Jako** [comment]
TV values should stay stable as far as I know, but I am not sure about this.

**Comment by Jako** [comment]
Maybe it is more an issue with jCrop, that can't work with that large images and that way the JSON in the TV input is not valid. The new Snippet code has some checks for that condition.

**Comment by vierkantemeter** [comment]
Thanks. Will check out 2.4.0 after my vacation (to :de:) . I'll let you know if this fixed it.

**Comment by vierkantemeter** [comment]
Hmm, I'm trying your 2.4.0-b4, but as soon as I open a resource in the manager with an image+ TV attatched to it, I got a blank manager screen. No errors in modx log and apache log.

MODX 2.4.2
Image+ 2.4.0-b4

**Comment by Jako** [comment]
Hmm, it works stable on my dev installation. Which thumbnail solution is installed?

**Comment by vierkantemeter** [comment]
Hi Jako,
Unfortunately I don't have time anymore to dig into this. You can close this issue unless someone else is having the same problem.

Thanks anyway!
