### ISSUE TITLE
Combine scripts and css

### ISSUE THREAD

**Issue by inreti** [Jako/ImagePlus#16]
Would be great to have the Imageplus JS files 
* imageplus.js
* imageplus.panel.js
* imageplus.window.editor.js
* imageplus.migx_renderer.js
* jquery.min.js
* jquery.jcrop.min.js
* imageplus.jquery.imagecrop.js

combined into one compressed file js-file.

Also the imageplus.css and jquery.jcrop.min.css can be compressed into one file at build time. They unlikely to change during releases.

The manager already has the drawback of loading a lot of data with load of roundtripts (esp. when compress_js is turned off as recommended). No need to add 7 more requests.

**Comment by Jako** [comment]
Done. Wait for the next beta.
