### ISSUE TITLE
Feature request: Make context setting set width and height or aspect ratio for cropping

### ISSUE THREAD

**Issue by mdehaan** [Jako/ImagePlus#21]
Is there a way to use a context setting to set the height and width or aspect ratio for the cropping?
For example if i make a context setting with the key header-image-width and put [[++header-image-width]] in the target image width on the tv input options, that would be nice.
But I know that doesn't work.
Is there a workaround for this?

Why I ask this is because I use MODX in a multisite setup.
So I have multiple contexts for multiple websites, and not each website needs the same height/width/aspect ratio.
The best way for us to configure most settings for the individual contexts/websites is by context settings.
I know that I could solve this with multiple TV's, but that wouldn't be the way I prefer to do it.

**Comment by Jako** [comment]
Will be available with version 2.6.0. A release candidate is available in https://github.com/Jako/ImagePlus/tree/master/_packages
