### ISSUE TITLE
Image output other than crobbed clipping 

### ISSUE THREAD

**Issue by navtsi** [Jako/ImagePlus#23]
If I place an image without any change of the crobbing everything works fine. But if I move the trimmed area the output shows a complete different result. The image gets vertically thinner. The rest of the image will be filled with white color.

**Auf Deutsch:** Wenn ich ein Bild auswähle und den Ausschnitt so übernehme wie es vorgeschlagen wird, passt alles. Aber sobald ich den Ausschnitt nach unten verschiebe, wird das Bild in der Höhe schmaler. Das sieht man auch schon in der Vorschau. Das geht im Extremfall bis einer 1Pixel hohen Linie.

01 Selecting image without changing the crobbed area 
![01-a](https://cloud.githubusercontent.com/assets/10669843/10695351/979c5e5a-79a3-11e5-9809-5e7c0488f68c.png)
![01-b](https://cloud.githubusercontent.com/assets/10669843/10695354/97baad88-79a3-11e5-9442-a92124c6b572.png)
![01-c](https://cloud.githubusercontent.com/assets/10669843/10695353/97ba76e2-79a3-11e5-9c10-ff3bbb0c6bce.png)

02 Move the crobbed area
![02-a](https://cloud.githubusercontent.com/assets/10669843/10695355/97bb1502-79a3-11e5-8679-2b77a9f0e93a.png)
![02-b](https://cloud.githubusercontent.com/assets/10669843/10695356/97bc77f8-79a3-11e5-8af0-8f347087d889.png)
![02-c](https://cloud.githubusercontent.com/assets/10669843/10695352/97ba881c-79a3-11e5-9423-f6e5408dca39.png)

**Comment by Jako** [comment]
Which MODX version do you use? There is an issue with internal phpthumb betweeen 2.3.6 and 2.4.1.

Removing the added line in https://github.com/modxcms/revolution/commit/8896c78a040e190e0548db7d9670aa771ef9a2ab should help.

**Comment by navtsi** [comment]
I used 2.4.1. After updating to 2.4.2 everything works fine. Thanks
