### ISSUE TITLE
Output Log Spam "[Image+] Unable to decode json - are you sure this is an Image+ TV?"

### ISSUE THREAD

**Issue by boformer** [Jako/ImagePlus#25]
The Image+ snippet should not output an error when the TV exists, but the value is empty (empty string).

See https://github.com/Jako/ImagePlus/blob/master/core/components/imageplus/elements/snippets/imageplus.snippet.php#L48

**Comment by Jako** [comment]
The Error is only triggered in that line, if no TV exists set with the parameter tvname.

You are using an old version of that package (https://github.com/alanpich/tvImagePlus/blob/59d1ba00ea15a8ebb4cebb1b961fff6473366bf1/core/components/tvimageplus/elements/snippets/image.php#L26). I can't fix that.
