### ISSUE TITLE
ImagePlus TV not loading properly

### ISSUE THREAD

**Issue by hugopeek** [Jako/ImagePlus#29]
I'm having a strange issue with the Image+ TV's in 1 install: they used to work, but are suddenly not showing their input field anymore. Just the labels.. In the source code, there's a piece of javascript that I think shouldn't be there, and is causing an Uncaught syntax error (see screen below).

It's the latest version, on latest MODX. I checked it in an almost identical install, and there it's working fine still, also after updating Image+ to 2.4.1.

And in this install there's a MIGX TV with an Image+ TV inside, which is working fine still. So Image+ does seem to be loading properly.

Do you have any idea what's going on here?

![image](https://cloud.githubusercontent.com/assets/5436121/12643383/096b834e-c5bc-11e5-8c7c-71660e93fcfa.png)

**Comment by Jako** [comment]
This should be the same issue as #22

I don't know how MIGX initalizes the Image+ TV but, somehow MIGX and Image+ don't work well together here.

**Comment by Jako** [comment]
I think it could be an issue with the media source, otherwise the $tvConfig array would be filled. So it should happen in this lines: https://github.com/Jako/ImagePlus/blob/master/core/components/imageplus/elements/tv/input/imageplus.class.php#L70-L76

**Comment by hugopeek** [comment]
Hmm ok, disabling MIGX and manually deleting the cache fixes this issue with the field not showing. Strangely enough though, the path is still visible at the top of the resource.

I will try to change a few settings for the media source both for this Image+ TV and the one inside MIGX.

**Comment by Jako** [comment]
Closed in favor of #22
