### ISSUE TITLE
@INHERIT binding doesn't work for Image+

### ISSUE THREAD

**Issue by WebraumZ** [Jako/ImagePlus#30]
Normally, when we use @INHERIT value with some TVs it automatically finds the corresponding value of parent TV and uses it as a default value for child resource. The problem is that Image+ outputs only "rough" value without any rendering process. In my case it was just string "@INHERIT" as output

**Comment by Jako** [comment]
**@INHERIT** works in my tests. It gets the right TV value of the parent. Maybe a typo in the default value of your TV? But the Snippet did not get the inherited value. Fixed with 2.4.2.

**Small hint:** If you set the output type to Image+, there is no "rough" value in the output.

**Comment by WebraumZ** [comment]
Thanks, Thomas) I'll check the new version
