### ISSUE TITLE
:notempty Output Modifier causes warning in MODX error log

### ISSUE THREAD

**Issue by digitalbricks** [Jako/ImagePlus#33]
When using the `:notempty` modifier in order to conditionally creating a specific image tag, i get the following warning:

> (ERROR in Image+ @ /index.php) The value is empty. Could not prepare the output.

Is there another way to check if the TV is empty?

In detail my code is the following:

     [[*NewsArticleImage:notempty=`<img src="[[*NewsArticleImage]]" alt="[[*pagetitle]]"  class="articleimage" width="240" height="180"/>`]]

BTW: Let me thank you for that great TV! I love the visual image cropping tool.

**Comment by digitalbricks** [comment]
Oh, i just saw that *every* call of an Image+ TV throws that warning if the TV is empty (image not set).
Shouldn't such call of an empty TV fail silent?

**Comment by Daruse93** [comment]
`(ERROR in Image+ @ /index.php) The value is empty. Could not prepare the output.`
Author, please fix it

**Comment by soopadave** [comment]
Keep the :notempty output modifier but try setting the Default Value (under Input Options) of the template variable to NULL - that should keep it from failing as it's actually returning *something* that the output modifier can deal with.

**Comment by Jako** [comment]
Fixed by changing the debug level in https://github.com/Jako/ImagePlus/commit/e4a63bb582c3e3420acf752cbda5477501fc985d

**Comment by Marduh** [comment]
(ERROR in Image+ @ /index.php) The value is empty. Could not prepare the output.

hello. every day in error log modx revo (2.5.0 pl, server: php7.0)
(ERROR in Image+ @ /index.php) The value is empty. Could not prepare the output.

**Comment by Jako** [comment]
It is fixed in https://github.com/Jako/ImagePlus/commit/e4a63bb582c3e3420acf752cbda5477501fc985d. I had no time to check and update the MODX package here and in the repository. So please apply the patch by yourself at the moment.
