### ISSUE TITLE
MIGX CMP Support?

### ISSUE THREAD

**Issue by Gibbs** [Jako/ImagePlus#34]
When adding ```imageplus``` to a CMP as a MIGX ```inputtvtype``` javascript errors are thrown. I appreciate this might not be directly a bug but was wondering if this is a known issue with any workarounds?

![](http://s17.postimg.org/phpikihbj/imageplus_migx.jpg)

Example code used by MIGX

```
{
      "MIGX_id":254,
      "field":"thumbnail_small",
      "caption":"Small Thumbnail",
      "description":"",
      "description_is_code":"0",
      "inputTV":"",
      "inputTVtype":"imageplus",
      "validation":"",
      "configs":"",
      "restrictive_condition":"",
      "display":"",
      "sourceFrom":"tv",
      "sources":"",
      "inputOptionValues":"",
      "default":"",
      "useDefaultIfEmpty":"0",
      "pos":6
}
```
 Using the TV directly in MIGX (```inputTV```) results in the same.

**Comment by Jako** [comment]
Could you try to add the following line in the ImagePlus plugin in the `OnManagerPageBeforeRender` section

```
$imageplus->includeScriptAssets();
```

**Comment by Gibbs** [comment]
That worked. Thanks Jako

**Comment by Jako** [comment]
Thanks for reporting back. It will be added in the next version.
