### ISSUE TITLE
Alt Tag - empty

### ISSUE THREAD

**Issue by natedin** [Jako/ImagePlus#35]
Hey,
I have an image+ I'm using the [[+alt]] tag to populate a heading on the page, if it's empty it defaults to *pagetitle, however it doesn't seem to be outputting anything.

In the tpl I have:
[[+alt:default=`[[*pagetitle]]`]]

If the alt tag is empty, it outputs nothing (so *pagetitle should take over). The only way I can find to get around this is to go into every page enter something into the alt field, save it, then delete it so the alt tag is empty. Then it seems to start working. (clear cache doesn't help either)

Thanks

**Comment by Jako** [comment]
Thats more a problem of the MODX parser and not the fault of Image+. Maybe it is solved with 2.5.
