### ISSUE TITLE
Possible problem with MODX 2.5

### ISSUE THREAD

**Issue by sonicpunk** [Jako/ImagePlus#37]
When I enable this plugin, suddenly I can no longer log into the MODX Manager.  The Manager Login just refreshes and nothing happens.  As the problem happened, I disabled all of my plugins one by one to see if a plugin was causing the problem.  I isolated it to image+.  Don't understand why. 

If I deactivate the plugin, I can log in.  Then I reactivate, it and it works fine.  But after I logout, the problem starts again.

**Comment by Jako** [comment]
Which MODX version? Which PHP Version?

**Comment by sonicpunk** [comment]
PHP 5.6 and MODX 2.5.... Really strange

**Comment by Jako** [comment]
Are you sure about this? I have noticed login problems with the Gallery plugin and "anonymous_sessions = 0" (https://github.com/modxcms/Gallery/issues/69). Could you get a php error log?

**Comment by Jako** [comment]
Have you emptied the core/cache folder after disabling the plugins during your tests? Just to be sure that you have caught the right plugin.

**Comment by sonicpunk** [comment]
Hi Jako,

Yes I did delete the core cache folder and browser cache, but it made no difference.  I will check it again this morning.

**Comment by sonicpunk** [comment]
Jako, do you use screen hero for screen sharing?  I could show you what is happening on my computer

**Comment by Jako** [comment]
Only a php error log would help at the moment. What you could do is disable all plugin events for the ImagePlus plugin and look if the problem still occurs, when the plugin is active. If not, which event is triggering the issue? This should help me a lot to narrow the issue down.

**Comment by sonicpunk** [comment]
It seems to be the system event "OnManagerPageBeforeRender".  I disabled that system event and now I can log in and out of the Manager without problems.

**Comment by Jako** [comment]
Suggested solution on https://github.com/modxcms/revolution/issues/12983#issuecomment-219218179
