### ISSUE TITLE
Alt tag field not showing in manager when manager language is other than English

### ISSUE THREAD

**Issue by vierkantemeter** [Jako/ImagePlus#4]
Hi, as reported earlier (https://github.com/alanpich/Image-Plus/issues/9), this bug is still present. Due to the hardcoded 'Yes' in the line beneath, the field for the alt tag disappear when manager language is set to other than English.

 ```$data->altTagOn = (isset($params['allowAltTag']) && $params['allowAltTag'] == 'Yes');``` (core/components/imageplus/model/imageplus/imageplus.class.php)

Quick fix: change 'Yes' to the yes of your language.

Image+ 2.3.2
MODX 2.3.3

**Comment by vierkantemeter** [comment]
Thanks! :+1:

**Comment by Jako** [comment]
Will be published in the next release.
