### ISSUE TITLE
 Could not unpack package imageplus-2.4.4

### ISSUE THREAD

**Issue by lwinds** [Jako/ImagePlus#40]
Help! It is impossible to establish the new version from modx.com
[2016-07-11 13:38:01] (ERROR @ /connectors/index.php) Could not unpack package .../core/packages/imageplus-2.4.4-pl.transport.zip to .../core/packages/. SIG: imageplus-2.4.4-pl
How it can be done on another?

**Comment by Jako** [comment]
Are you sure that it is an issue with the package? Maybe it is an issue with the provider.

The packages could be downloaded from https://github.com/Jako/ImagePlus/tree/master/_packages and uploaded in the backend.

**Comment by lwinds** [comment]
I have downloaded a package imageplus-2.4.4-pl then I have copied in the folder ../core/packages
And again this error!  My version imageplus-2.4.3 works well. I can't be updated.
[2016-07-13 22:50:56] (ERROR @ /connectors/index.php) Could not unpack package .../core/packages/imageplus-2.4.4-pl.transport.zip to .../core/packages/. SIG: imageplus-2.4.4-pl

**Comment by Jako** [comment]
Could you install other packages? If not, is your core/packages folder writable for PHP?

**Comment by lwinds** [comment]
I have completely removed all packages  imageplus. I have downloaded here https://github.com/Jako/ImagePlus/tree/master/_packages imageplus-2.4.4 and imageplus-2.4.3 . The package of version 2,4,3 is installed well!   Package of version 2.4.4 gives an error message.

**Comment by Jako** [comment]
Strange, I have installed the package from modx.com on a host I currently work on without a problem.

Please mail me directly (contact info is on my github page) and I send you (tomorrow) a fresh built package.

**Comment by Jako** [comment]
Could you please remove the downloaded 2.4.4 transport package file and the according extracted 2.4.4 folder from core/packages

**Comment by lwinds** [comment]
Thanks for the help! I'll be waiting  lwindmax@gmail.com

**Comment by natedin** [comment]
Unfortunately I'm having the same problem:
_"Could not install package with signature: imageplus-2.4.4-pl"_

MODX error log:
_[2016-07-26 15:54:43] (ERROR @ E:\wamp\www\sos\core\xpdo\transport\xpdotransport.class.php : 682) Could not unpack package E:/wamp/www/sos/core/packages/imageplus-2.4.4-pl.transport.zip to E:/wamp/www/sos/core/packages/. SIG: imageplus-2.4.4-pl_

- MODX 2.5.0
- Image+ 2.4.4

Have other packages installed with no problem Redactor, Quickstart buttons, Wayfinder etc. Let me know if you need any other info to help debug

I've installed Image+ 2.4.3 for now (which worked fine)

Thanks

**Comment by Jako** [comment]
I have uploaded a new file to MODX Extras. Maybe it is solved with that.

If not: please tell me your PHP Version, host system, Apache zip extension version etc.

**Comment by Jako** [comment]
Should be solved with 2.4.5. I can't upload that at the moment to MODX extras, but you could install the package from https://github.com/Jako/ImagePlus/tree/master/_packages

**Comment by lwinds** [comment]
Version 2.4.5 installed successfully! Thanks!
