### ISSUE TITLE
Generate Thumb URL not working

### ISSUE THREAD

**Issue by johnmacdonald3000** [Jako/ImagePlus#43]
Generate Thumb URL setting (in Output options). When I set it to "Yes", save and reopen the TV, it's set back to "No."

MODX 2.5.1, ImagePlus 2.4.5, 2 different sites

**Comment by Jako** [comment]
This is fixed in the next version.

**Comment by johnmacdonald3000** [comment]
Super! Thanks.

**Comment by Jako** [comment]
2.6.0-rc3 is available for testing: https://github.com/Jako/ImagePlus/blob/master/_packages/imageplus-2.6.0-rc3.transport.zip
