### ISSUE TITLE
Issue with placeholder

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ImagePlus#44]
The `source.src` placeholder does not seem to work. It outputs the same value that is stored within `url`

**Comment by Jako** [comment]
Could you check if it is solved with: https://github.com/Jako/ImagePlus/blob/master/_packages/imageplus-2.6.0-rc3.transport.zip

**Comment by Jako** [comment]
Closing due to lack of feedback. If it is still an issue, feel free to reopen.

**Comment by pmacswebteam** [comment]
*UPDATE*: It seems as if upgrading the package has solved this issue, thanks!
