### ISSUE TITLE
Display issue with MODX 2.5.2 

### ISSUE THREAD

**Issue by sonicpunk** [Jako/ImagePlus#48]
I have the problem that there is an error in the MODX interface
![screen shot 2016-12-23 at 14 07 48](https://cloud.githubusercontent.com/assets/447453/21458772/8d3b34e0-c939-11e6-91de-191ea28b4d10.png)

In the hidden input the json is written twice

![screen shot 2016-12-23 at 18 00 19](https://cloud.githubusercontent.com/assets/447453/21458794/b44de1c2-c939-11e6-8918-56a149450abc.png)

**Comment by Jako** [comment]
Not sure what is happening there. Have you tried to reinstall it? Are there errors with overwriting files?

Could you please post the real html source code of the Image+ TV here. It looks like this: 
```
<div class="x-form-element modx-tv-form-element">
    <input type="hidden" id="tvdef1" value=""/>
    <textarea class="imageplus-hidden-textarea" name="tv1" id="tv1">{
  "sourceImg": {
    "src": "image.jpg",
    "width": 600,
    "height": 450,
    "source": 1
  },
  "crop": {
    "x": 0,
    "y": 0,
    "width": 600,
    "height": 400
  },
  "targetWidth": 0,
  "targetHeight": 200
}</textarea>
    <div id="imageplus-panel-input-div-1" class="imageplus-panel-input"></div>
    <script type="text/javascript">
        Ext.onReady(function () {
            MODx.load({
                xtype: 'imageplus-panel-input',
                renderTo: 'imageplus-panel-input-div-1',
                options: {"allowBlank":true,"targetWidth":0,"targetHeight":200,"targetRatio":"1.5","thumbnailWidth":200,"altTagOn":true,"captionOn":false,"creditsOn":false,"mediaSource":1,"tvId":1,"tvParams":[""]},
                hiddenField: 'tv1'
            });
        });
    </script>
</div>
```

**Comment by sonicpunk** [comment]
Yes, I have deinstalled and reinstalled.  On my local server it is working properly

`    <div id="modx-tv-tab15" class="x-tab" title="Header">
        <div class="x-form-item x-tab-item  modx-tv tv-first" id="tv6-tr">
        <label for="tv6" class="x-form-item-label modx-tv-label">
            <div class="modx-tv-label-title">
                                <span class="modx-tv-caption" id="tv6-caption">Header Bild</span>
            </div>
            <a class="modx-tv-reset" id="modx-tv-reset-6" title="Set to Default"></a>
                    </label>
                <div class="x-form-element modx-tv-form-element">
            <input type="hidden" id="tvdef6" value="" />
            <input type="hidden" name="tv6" id="tv6" value="{
  "sourceImg": {
    "width": 2448,
    "height": 3264,
    "src": "bilder/Bienen-Ragwurz.JPG",
    "source": 2
  },
  "crop": {
    "width": 1200,
    "height": 900,
    "x": 0,
    "y": 0
  },
  "targetWidth": 900,
  "targetHeight": 320,
  "altTag": false
}" />
<div id="tvimageplus-panel-input-div-6" style="width:420px; margin-top:-16px;"></div>`

**Comment by sonicpunk** [comment]
´´´
<script type="text/javascript">

Ext.onReady(function(){ 
    MODx.load({   
            xtype: 'tvimageplus-panel-input'
            ,renderTo: 'tvimageplus-panel-input-div-6'
            ,tvimageplus: {"mediaSource":2,"tv":{"id":6,"params":[""],"value":"{\r\n  \"sourceImg\": {\r\n    \"width\": 2448,\r\n    \"height\": 3264,\r\n    \"src\": \"bilder\/Bienen-Ragwurz.JPG\",\r\n    \"source\": 2\r\n  },\r\n  \"crop\": {\r\n    \"width\": 1200,\r\n    \"height\": 900,\r\n    \"x\": 0,\r\n    \"y\": 0\r\n  },\r\n  \"targetWidth\": 900,\r\n  \"targetHeight\": 320,\r\n  \"altTag\": false\r\n}"},"allowBlank":true,"targetWidth":900,"targetHeight":320,"altTagOn":false,"crop":{"width":1200,"height":900,"x":0,"y":0},"sourceImg":{"width":2448,"height":3264,"src":"bilder\/Bienen-Ragwurz.JPG","source":2},"altTag":false}
            ,updateTo: 'tv6'  
        });
 });

$.merge(true,tvImagePlus.config,{"core_path":"\/kunden\/xxxxx\/webseiten\/production\/private\/components\/tvimageplus\/","assets_url":"\/assets\/components\/tvimageplus\/","connectorUrl":"\/assets\/components\/tvimageplus\/mgr\/connector.php","sources":{"1":{"url":"\/"},"2":{"url":"\/assets\/webmaster\/"}},"crop_icon":"\/assets\/components\/tvimageplus\/mgr\/icons\/icon.crop.png","has_unmet_dependencies":false,"lexicon":{"imageplus":"Image+","tvimageplus.editor_title":"Image+ Editor","tvimageplus.edit_image":"Edit Image","tvimageplus.targetwidth":"Target Width","tvimageplus.targetwidth_desc":"The target width for the output image","tvimageplus.targetheight":"Target Height","tvimageplus.targetheight_desc":"The target height for the output image","tvimageplus.allowAltTag":"Alt tag field","tvimageplus.allowAltTag_desc":"Allow user to enter a title\/alt-tag for the image","tvimageplus.phpThumbParams":"Additional phpThumb parameters","tvimageplus.phpThumbParams_desc":"Add additional filters etc for phpThumb. Documentation can be found <a target=\"_blank\" href=\"http:\/\/phpthumb.sourceforge.net\/demo\/docs\/phpthumb.readme.txt\">here<\/a>.","tvimageplus.outputChunk":"Output chunk","tvimageplus.outputChunk_desc":"Select a chunk for tv output. Leave blank for raw url output"}});
</script>
´´´

**Comment by Jako** [comment]
The code looks like a very old Image+ Version (2.2.2).

https://github.com/Jako/ImagePlus/blob/d589be4657a8dcdb13e09139bb2834d904756071/core/components/imageplus/elements/tv/input/tpl/imageplus.inputrender.tpl

There is no $.merge after 2.3.3.

**Comment by Jako** [comment]
Maybe you have installed multiple ImagePlus versions or an old ImagePlus plugin is active.

**Comment by sonicpunk** [comment]
That is exactly correct.  It is strange that is only happened on the production server and not on my local one.  But I deleted the Beta 2.2 Version of the plugin and now everything is hunky-dory!

**Comment by Jako** [comment]
The strange issue could have happened because of a different plugin order. Maybe the execution of both plugins was swapped on the production host.
