### ISSUE TITLE
ImagePlus with really small image

### ISSUE THREAD

**Issue by lawebfabric** [Jako/ImagePlus#53]
When i used ImagePlus with really small config and images, the window won't fully display zoom crop window. Update button won't appear completely.

**Comment by Jako** [comment]
Fixed with 2.8.0

**Comment by Jako** [comment]
You could you try the 2.8.0-rc1: https://github.com/Jako/ImagePlus/raw/master/_packages/imageplus-2.8.0-rc1.transport.zip
