### ISSUE TITLE
Feature request: Parameter for full site URL

### ISSUE THREAD

**Issue by itsmerobliberty** [Jako/ImagePlus#58]
Currently the output uses the relative path: /assets/images/myimage.jpg but it would be awesome if a &path=`full` parameter was added so the output could be http://mysite.com/assets/images/myimage.jpg

**Comment by Jako** [comment]
This could be bypassed by setting an [Output Chunk](http://jako.github.io/ImagePlus/usage/#output-chunk) and prepend the `[[++site_url]]` in there before `[[+url]]`

**Comment by itsmerobliberty** [comment]
this makes a double /, breaking the URL, because [[++site_url]] ends with one and [[+url]] starts with one.

**Comment by Jako** [comment]
Then trim one of both placeholders with ```[[++site_url:rtrim=`/`]]``` or ```[[+url:ltrim=`/`]]``` and a ltrim (rtrim is similar) snippet based output modifier: 
```
<?php return ($options) ? ltrim($input, $options) : ltrim($input, $options);
```
