### ISSUE TITLE
Image+ outputs full server path/nothing is shown

### ISSUE THREAD

**Issue by mdillgen** [Jako/ImagePlus#59]
The following topic was already mentioned in another thread and was closed. But i still run into this issue and after hours of testing i couldn’t come up with any solution.

The problem is, that my image+ tv outputs the full server path when i call it via ImagePlus Snippet call.

_Following scenarios:_

No special Media Source given (fresh MODX install). phpThumbsUp is installed as thumbnail generator.

**TV (img-01)**
_Input Options:_
Image+
_Output Options:_
Image+ 
_Output Chunk:_ 
img-01-tpl 

**Chunk (img-01-tpl)**
```
<img src="[[+url:phpthumbsup=`[[+crop.options]]&w=1280`]]" alt="[[+alt]]"/>
```

**Output call (Template)**
```
[[*img-01]]
```

**Output (Frontend)**
```
<img src="/phpthumbsup/sx/0/sy/313/sw/500/sh/312/w/1280/src/assets/images/img01.png" alt="test“>
```

**This works as expected!**

**TV (img-02)**
_Input Options:_ 
Image+
_Output Options:_ 
Image+
_Output Chunk:_ 
img-02-tpl 

**Chunk (img-02-tpl)**
```
<img src="[[+url:phpthumbsup=`[[+crop.options]]&w=1280`]]" alt="[[+alt]]"/>
```

**Output call (Template)**
```
[[ImagePlus?
  &tvname=`img-02`
  &type=`tpl`
  &tpl=`img-02-tpl`
]]
```

**Output (Frontend)**
```
<img src="/phpthumbsup/sx/0/sy/313/sw/500/sh/312/w/1280/src/_Users/username/desktop/testsite/_assets/images/img02.png“ alt="test">
```

**As you can see, in this example the full server path is generated in the frontend and the image isn’t shown.**

**Comment by Jako** [comment]
Does the image `_assets/images/img02.png` exist? If it does not exist, it should be more an issue of phpThumbsUp because of this line: https://github.com/Jako/ImagePlus/blob/master/core/components/imageplus/model/cropengines/PhpThumbsUp.php#L145

Image+ does not create any full server path then. It only passes the relative path on base of the media source to the url placeholder if the image does not exist.

**Comment by mdillgen** [comment]
Thanks for your quick reply @Jako 
But, unfortunately i couldn’t figure out any solution. The Image exists for sure. My examples were just for demonstration purposes. Therefore i created 2 examples of same working images, tv’s and chunks with the suffixes -01 and -02. It is only the different output call. I have the same problem other sites, too. 

As i tried to explain, the first example is working (call the TV directly in the template). It uses phpthumpsup and is working very well. The second example isn’t working (call exactly the same but via Image+ Output snippet). 

_Sorry, in my 2nd example the underscores in the Frontend output code example doesn’t exist, it was just a formating mistake._

So, call the TV which takes a output chunk gives:
`<img src="/phpthumbsup/sx/0/sy/313/sw/500/sh/312/w/1280/src/assets/images/img01.png" alt="test“>
`


Image+ snippet call, which also takes the TV and the Output chunk gives:
`<img src="/phpthumbsup/sx/0/sy/313/sw/500/sh/312/w/1280/src/Users/username/desktop/testsite/assets/images/img01.png" alt="test“>`

**Comment by mdillgen** [comment]
Thanks a lot to @Jako for fixing this in version 2.6.3. !
