### ISSUE TITLE
MODX 2.6.0: inserting images not possible

### ISSUE THREAD

**Issue by mcnickel** [Jako/ImagePlus#62]
When inserting a new image into a TV, the message "image too small" appears.
After removing the target width/height, image can be inserted and cropped, but image+ pics only the upper left corner of the image, regardless of the selected part of the image.

Already existing/inserted images can be cropped. No error.

Tested in two installations with PHP 5.6.31 / 7.0.23 / 7.1.9.
Worked right until update to 2.6.0.

**Comment by labr1005** [comment]
Confirmed.
Related to https://github.com/modxcms/revolution/issues/13670.
I'm working on a fix.

**Comment by labr1005** [comment]
Will be fixed with this PR https://github.com/modxcms/revolution/pull/13672

**Comment by Jako** [comment]
Will be fixed in 2.6.1
