### ISSUE TITLE
Crop bug

### ISSUE THREAD

**Issue by sergnewman** [Jako/ImagePlus#69]
Hi, Jako!
I found some buggz(
https://youtu.be/gV_gH9PxfNQ
https://www.youtube.com/watch?v=ZKJiN2Uh-t0
And thank you friend for my fav MODX-Extra!

**Comment by Jako** [comment]
If you are on Revo 2.6.0, please update to 2.6.1 - this is a [known](https://github.com/Jako/ImagePlus/issues/62) issue then.

**Comment by c0mat0se** [comment]
I still have this issue in 2.6.1, referring to the bug found in @sergnewman first video (https://youtu.be/gV_gH9PxfNQ).

**Comment by Esger** [comment]
I have something similar in modx 3.01.. The initial crop is very small (when I select an image and don't change the cropping)
I have to reopen the croptool and maximize the crop-selection to get the whole image. (not all images need cropping)

.. and there is an unneeded scroll-bar over the right side of the image which I can of course hide by adding 
`.x-window .x-window-body.x-window-body{overflow:hidden}` to the css but that will disappear when I update the extra.

**Comment by Jako** [comment]
This is solved with 2.9.1.
