### ISSUE TITLE
Different crop options for <picture> element

### ISSUE THREAD

**Issue by c0mat0se** [Jako/ImagePlus#70]
Is there any way to pass through different `&options` for different screen widths in the image+ call?

For instance,
If I have a <picture> element like:
``
<picture>
    <source srcset="[[+url:pthumb=`[[+crop.options2]]`]]" media="(max-width: 640px)">
    <source srcset="[[+url:pthumb=`[[+crop.options1]]`]]">
    <img src="[[+url]]" alt="[[+alt]]"/>
</picture>
``

My image+ call could look something like:
``
[[ImagePlus? &tvname=`tv` &docid=`[[*id]]` &type=`tpl` &tpl=`ImagePlus.image` &options1=`w=1200` &options2=`w=640`]]
``

This way I could setup a global image+ chunk called ImagePlus.image and pass any of my media queries through it with ease.

**Comment by Jako** [comment]
Please try ```[[+url:pthumb=`[[+options2]]`]]```. I hope additional snippet properties are available inside. If this does not work, it is not difficult, to make it possible.

**Comment by c0mat0se** [comment]
Wow! That works perfectly! This is amazing! Thank you.
