### ISSUE TITLE
Cropping fails when target width is same as image width

### ISSUE THREAD

**Issue by SnowCreative** [Jako/ImagePlus#73]
I'm getting an error when I use ImagePlus to crop photos that are the same width as the target width in the TV. Height does not matter, nor does target aspect ratio. 

**To Test:**

1. Set up a TV, set the target width to 1024, and height to something less than the height of the images on the server.

2. Select a photo that is 1024 pixels wide, and crop it

3. The thumbnail that appears will be weird, one image inset in another. The coordinates entered in the TV will be wrong, with the starting x coordinate -1 rather than 0.

Here's what my thumbnails look like:

![thumbnail-sample](https://user-images.githubusercontent.com/2528374/44950886-002efa80-ae22-11e8-85f9-51d1f32cf622.jpg)

**Here's the error in my error log:**

(ERROR @ /home/nedccor/modxcoretest/components/phpthumbof/model/phpthumbof.class.php : 156) [pThumb] Resource: 10 || Image: /home/nedccor/test/assets/media/images/header_images/Head-Abt-Overv-rolled-docs.jpg
Could not cache thumbnail to file at: /home/nedccor/test/assets/components/phpthumbof/cache/Head-Abt-Overv-rolled-docs.0bed75c99b0c0402282346970401c03b.jpg
Resizer debug output:
    [0] => Resizer v1.0.1
    [1] => Using GD
    [2] => Input file: /home/nedccor/test/assets/media/images/header_images/Head-Abt-Overv-rolled-docs.jpg
    [3] => Input options: 
  'sx' => '-1',
  'sy' => '173',
  'sw' => '1024',
  'sh' => '452',
  'w' => '1024',
  'h' => '452',
  'far' => '1',
  'f' => 'jpeg'
    [4] => *** Error *** A coordinate cannot be positioned outside of a bounding box

**Comment by Jako** [comment]
This is solved with 2.9.1.
