### ISSUE TITLE
Image+ TV seems to no longer work in a context

### ISSUE THREAD

**Issue by pmacswebteam** [Jako/ImagePlus#77]
When using the image+ TV type in a context, the following errors occur:

1. When adding an image that is the correct height & width set within the TV, a pop-up arises that the image is too small, however, you can click past it and continue to edit the image:
<img width="1054" alt="screen shot 2019-01-02 at 10 43 19 am" src="https://user-images.githubusercontent.com/12412403/50599178-47360680-0e7b-11e9-91f2-7ed79e62ea43.png">

2.  When selecting the image, a broken image thumbnail icon appears in the manager view:
<img width="710" alt="screen shot 2019-01-02 at 10 44 41 am" src="https://user-images.githubusercontent.com/12412403/50599249-7d738600-0e7b-11e9-8ce9-7bb50dc6194f.png">

3. When saving & viewing the resource, the image seems to appear correctly on the page, however, when choosing a new image using the same image+ TV, after saving and viewing, the following error appears on the rendered page: `Image+ Error: Invalid Media Source`, and the TV disappears from the manager view after refreshing the page (Note: we are using ToggleTVSet to display several banner options for the page):
<img width="749" alt="screen shot 2019-01-02 at 10 48 35 am" src="https://user-images.githubusercontent.com/12412403/50599430-11dde880-0e7c-11e9-9a19-d6537bbb7933.png">

**Comment by Jako** [comment]
Sorry for the late respone: Have you moved the resource from a different context? Do you have the same issue with a new template variable? A reason could be: Image+ saves the media source in the json of the template variable value. So if you move the resource to a different context, the media source value could point to an invalid context.

**Comment by pmacswebteam** [comment]
Hi - it seems like we are no longer experiencing this issue, thanks!
